#!/usr/bin/env python3
"""Build a static HTML presentation site for active RTS Markdown docs."""

from __future__ import annotations

import html
import json
import os
import re
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import markdown


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "html"
ASSETS = OUT / "assets"
MARKER = OUT / ".rts-html-generated"

EXCLUDED_PREFIXES = ("docs/archive/", "archive/", "html/")
EXCLUDED_PARTS = {".git", ".gradle", ".idea", "build", "target"}

ORDERED_DOCS = [
    "README.md",
    "AGENTS.md",
    "docs/INDEX.md",
    "docs/confirmed/README.md",
    "docs/confirmed/project-alignment-summary-zh.md",
    "docs/confirmed/system-constitution-v1.md",
    "docs/confirmed/kb-to-index-projection-contract-zh.md",
    "docs/confirmed/llm-harness-and-agent-integration-alignment-zh.md",
    "docs/confirmed/internal-llm-agent-service-implementation-plan-zh.md",
    "docs/confirmed/day1-query-service-and-llm-harness-plan-zh.md",
    "docs/confirmed/day2-agentic-retrieval-evolution-plan-zh.md",
    "docs/confirmed/final-llm-agent-service-plan-zh.md",
    "docs/confirmed/document-decision-register-zh.md",
    "docs/java-service-runbook-zh.md",
    "docs/api-caller-guide-zh.md",
    "docs/day1-sample-pack-test-commands.md",
    "docs/reference/README.md",
]

CATEGORY_RANK = {
    "Entry": 0,
    "Agent Guide": 1,
    "Navigation": 2,
    "Confirmed Baseline": 3,
    "Operational": 4,
    "Reference": 5,
    "KB Pack": 6,
    "Other Active": 7,
}

DOCMETA_RE = re.compile(r"^\s*<!--\s*docmeta\s*\n(.*?)\n-->\s*", re.DOTALL)
MD_LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")


@dataclass
class Doc:
    source_path: Path
    rel_path: str
    output_path: Path
    title: str
    summary: str
    category: str
    meta: dict[str, Any]
    body_markdown: str
    body_html: str = ""
    toc_html: str = ""


def main() -> None:
    docs = load_docs()
    docs_by_rel = {doc.rel_path: doc for doc in docs}

    prepare_output_dir()
    write_assets(docs)

    for doc in docs:
        render_markdown_doc(doc, docs_by_rel)
        write_doc_page(doc, docs, docs_by_rel)

    write_index(docs)
    MARKER.write_text("generated by tools/build_html_docs.py\n", encoding="utf-8")
    print(f"Generated {len(docs)} document pages under {OUT.relative_to(ROOT)}")


def load_docs() -> list[Doc]:
    docs: list[Doc] = []
    for path in ROOT.rglob("*.md"):
        if not is_active_markdown(path):
            continue
        rel_path = path.relative_to(ROOT).as_posix()
        raw = path.read_text(encoding="utf-8")
        meta, body = split_docmeta(raw)
        title = extract_title(body) or path.stem.replace("-", " ").title()
        summary = str(meta.get("summary") or extract_first_paragraph(body) or "")
        docs.append(
            Doc(
                source_path=path,
                rel_path=rel_path,
                output_path=OUT / Path(rel_path).with_suffix(".html"),
                title=title,
                summary=summary,
                category=category_for(rel_path),
                meta=meta,
                body_markdown=body,
            )
        )
    docs.sort(key=sort_key)
    return docs


def is_active_markdown(path: Path) -> bool:
    rel = path.relative_to(ROOT).as_posix()
    if any(rel.startswith(prefix) for prefix in EXCLUDED_PREFIXES):
        return False
    if any(part in EXCLUDED_PARTS for part in path.relative_to(ROOT).parts):
        return False
    return True


def split_docmeta(raw: str) -> tuple[dict[str, Any], str]:
    match = DOCMETA_RE.match(raw)
    if not match:
        return {}, raw.lstrip()
    return parse_docmeta(match.group(1)), raw[match.end() :].lstrip()


def parse_docmeta(block: str) -> dict[str, Any]:
    meta: dict[str, Any] = {}
    current_key: str | None = None
    for line in block.splitlines():
        if not line.strip():
            continue
        key_match = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if key_match:
            current_key = key_match.group(1)
            value = key_match.group(2).strip()
            meta[current_key] = value if value else []
            continue
        stripped = line.strip()
        if stripped.startswith("- ") and current_key:
            current_value = meta.setdefault(current_key, [])
            if not isinstance(current_value, list):
                current_value = [str(current_value)]
                meta[current_key] = current_value
            current_value.append(stripped[2:].strip())
    return meta


def extract_title(markdown_text: str) -> str:
    for line in markdown_text.splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return strip_markdown_inline(match.group(1))
    return ""


def extract_first_paragraph(markdown_text: str) -> str:
    lines: list[str] = []
    in_code = False
    for line in markdown_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code = not in_code
            continue
        if in_code or not stripped:
            if lines:
                break
            continue
        if stripped.startswith(("#", "-", ">", "|")):
            continue
        lines.append(stripped)
    return strip_markdown_inline(" ".join(lines))


def strip_markdown_inline(text: str) -> str:
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    return text.strip()


def category_for(rel_path: str) -> str:
    if rel_path == "README.md":
        return "Entry"
    if rel_path == "AGENTS.md":
        return "Agent Guide"
    if rel_path == "docs/INDEX.md":
        return "Navigation"
    if rel_path.startswith("docs/confirmed/"):
        return "Confirmed Baseline"
    if rel_path in {
        "docs/java-service-runbook-zh.md",
        "docs/api-caller-guide-zh.md",
        "docs/day1-sample-pack-test-commands.md",
    }:
        return "Operational"
    if rel_path.startswith("docs/reference/"):
        return "Reference"
    if rel_path.startswith("kb/"):
        return "KB Pack"
    return "Other Active"


def sort_key(doc: Doc) -> tuple[int, int, str]:
    ordered = {name: index for index, name in enumerate(ORDERED_DOCS)}
    explicit = ordered.get(doc.rel_path, 10_000)
    return (CATEGORY_RANK.get(doc.category, 99), explicit, doc.rel_path)


def prepare_output_dir() -> None:
    if OUT.exists():
        has_files = any(OUT.iterdir())
        if has_files and not MARKER.exists():
            raise SystemExit(
                f"{OUT} already contains files and is not marked as generated. "
                "Move or remove it before rebuilding."
            )
        shutil.rmtree(OUT)
    ASSETS.mkdir(parents=True, exist_ok=True)


def render_markdown_doc(doc: Doc, docs_by_rel: dict[str, Doc]) -> None:
    rewritten = rewrite_markdown_links(doc.body_markdown, doc, docs_by_rel)
    converter = markdown.Markdown(
        extensions=["extra", "toc", "sane_lists"],
        extension_configs={
            "toc": {
                "permalink": "#",
                "toc_depth": "2-4",
            }
        },
        output_format="html5",
    )
    doc.body_html = converter.convert(rewritten)
    doc.toc_html = converter.toc


def rewrite_markdown_links(markdown_text: str, doc: Doc, docs_by_rel: dict[str, Doc]) -> str:
    def replace(match: re.Match[str]) -> str:
        label, raw_url = match.groups()
        raw_url = raw_url.strip()
        if re.match(r"^(https?:|mailto:|#|javascript:)", raw_url):
            return match.group(0)
        path_part, fragment = split_fragment(raw_url)
        if not path_part:
            return match.group(0)
        target = (doc.source_path.parent / path_part).resolve()
        try:
            target_rel = target.relative_to(ROOT).as_posix()
        except ValueError:
            return match.group(0)
        target_doc = docs_by_rel.get(target_rel)
        if target_doc:
            href = rel_url(doc.output_path, target_doc.output_path) + fragment
        elif target.exists():
            href = rel_url(doc.output_path, target) + fragment
        else:
            title = esc(f"Missing local target: {raw_url}")
            return f'<span class="missing-link" title="{title}">{label}</span>'
        return f"[{label}]({href})"

    return MD_LINK_RE.sub(replace, markdown_text)


def split_fragment(url: str) -> tuple[str, str]:
    if "#" not in url:
        return url, ""
    path_part, fragment = url.split("#", 1)
    return path_part, f"#{fragment}"


def rel_url(from_file: Path, to_path: Path) -> str:
    return os.path.relpath(to_path, from_file.parent).replace(os.sep, "/")


def write_doc_page(doc: Doc, docs: list[Doc], docs_by_rel: dict[str, Doc]) -> None:
    doc.output_path.parent.mkdir(parents=True, exist_ok=True)
    css_href = rel_url(doc.output_path, ASSETS / "styles.css")
    js_href = rel_url(doc.output_path, ASSETS / "app.js")
    home_href = rel_url(doc.output_path, OUT / "index.html")
    source_href = rel_url(doc.output_path, doc.source_path)
    page_title = f"{doc.title} | RTS HTML Docs"
    nav_items = render_side_nav(doc, docs)
    meta_panel = render_meta_panel(doc, docs_by_rel)
    toc = doc.toc_html or '<p class="empty-note">这篇文档没有二级标题。</p>'
    body = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(page_title)}</title>
  <link rel="stylesheet" href="{css_href}">
</head>
<body class="doc-page">
  <a class="skip-link" href="#content">跳到正文</a>
  <header class="topbar">
    <a class="brand" href="{home_href}">RTS Docs</a>
    <nav class="topnav" aria-label="文档导航">
      <a href="{home_href}">总入口</a>
      <a href="{source_href}">查看 Markdown 源文件</a>
    </nav>
  </header>
  <main class="doc-shell">
    <aside class="doc-sidebar" aria-label="文档侧栏">
      <section class="sidebar-card">
        <p class="eyebrow">当前文档</p>
        <h2>{esc(doc.title)}</h2>
        <p>{esc(doc.summary)}</p>
        <div class="chip-row">
          <span class="chip">{esc(doc.category)}</span>
          {render_meta_chip("role", doc.meta.get("role"))}
          {render_meta_chip("layer", doc.meta.get("layer"))}
        </div>
      </section>
      <section class="sidebar-card toc-card">
        <p class="eyebrow">页面目录</p>
        {toc}
      </section>
      {meta_panel}
      <section class="sidebar-card">
        <p class="eyebrow">同组文档</p>
        <div class="mini-nav">{nav_items}</div>
      </section>
    </aside>
    <article class="doc-content" id="content">
      <section class="doc-hero">
        <p class="eyebrow">{esc(doc.category)} · {esc(doc.rel_path)}</p>
        <h1>{esc(doc.title)}</h1>
        <p>{esc(doc.summary)}</p>
      </section>
      <section class="source-note">
        <strong>准确性说明：</strong>正文来自对应 Markdown 原文；本 HTML 页只增加目录、阅读提示、样式和交互，不改变文档事实边界。
      </section>
      <div class="markdown-body">
        {doc.body_html}
      </div>
    </article>
  </main>
  <script src="{js_href}"></script>
</body>
</html>
"""
    doc.output_path.write_text(body, encoding="utf-8")


def render_meta_chip(label: str, value: Any) -> str:
    if value in (None, "", []):
        return ""
    if isinstance(value, list):
        value = ", ".join(value)
    return f'<span class="chip subtle">{esc(label)}: {esc(str(value))}</span>'


def render_meta_panel(doc: Doc, docs_by_rel: dict[str, Doc]) -> str:
    read_when = render_meta_list("适合阅读", doc.meta.get("read_when"), docs_by_rel, doc.output_path)
    skip_when = render_meta_list("可跳过", doc.meta.get("skip_when"), docs_by_rel, doc.output_path)
    sources = render_meta_list("权威来源 / 关联来源", doc.meta.get("source_of_truth"), docs_by_rel, doc.output_path)
    if not any([read_when, skip_when, sources]):
        return ""
    return f"""<section class="sidebar-card meta-card">
      <p class="eyebrow">阅读提示</p>
      {read_when}
      {skip_when}
      {sources}
    </section>"""


def render_meta_list(
    title: str,
    values: Any,
    docs_by_rel: dict[str, Doc],
    current_output: Path,
) -> str:
    if not values:
        return ""
    if isinstance(values, str):
        values = [values]
    items = "\n".join(f"<li>{render_meta_value(v, docs_by_rel, current_output)}</li>" for v in values)
    return f"<h3>{esc(title)}</h3><ul>{items}</ul>"


def render_meta_value(value: str, docs_by_rel: dict[str, Doc], current_output: Path) -> str:
    clean = value.strip().strip("`")
    target = docs_by_rel.get(clean)
    if target:
        href = rel_url(current_output, target.output_path)
        return f'<a href="{href}">{esc(clean)}</a>'
    return esc(value)


def render_side_nav(doc: Doc, docs: list[Doc]) -> str:
    peers = [item for item in docs if item.category == doc.category]
    if len(peers) <= 1:
        return '<p class="empty-note">暂无同组文档。</p>'
    links = []
    for peer in peers[:14]:
        href = rel_url(doc.output_path, peer.output_path)
        active = " active" if peer.rel_path == doc.rel_path else ""
        links.append(f'<a class="mini-link{active}" href="{href}">{esc(peer.title)}</a>')
    return "\n".join(links)


def write_index(docs: list[Doc]) -> None:
    index_path = OUT / "index.html"
    cards = "\n".join(render_doc_card(doc, index_path) for doc in docs)
    counts = category_counts(docs)
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    category_buttons = "\n".join(
        f'<button class="filter-pill" type="button" data-filter="{esc(category)}">{esc(category)} <span>{count}</span></button>'
        for category, count in counts.items()
    )
    baseline_links = render_baseline_route(docs, index_path)
    body = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RTS HTML Docs</title>
  <link rel="stylesheet" href="assets/styles.css">
</head>
<body class="home-page">
  <header class="home-hero">
    <nav class="hero-nav" aria-label="站点导航">
      <a class="brand" href="index.html">RTS Docs</a>
      <a href="#docs">文档列表</a>
      <a href="#examples">交互示例</a>
      <a href="../README.md">Markdown README</a>
    </nav>
    <div class="hero-grid">
      <section>
        <p class="eyebrow">Static HTML Presentation</p>
        <h1>RTS 活跃文档 HTML 中心</h1>
        <p class="hero-lede">这里把非归档 Markdown 文档转换为可浏览、可搜索、可复制示例的静态 HTML。正文忠实来自原 Markdown，页面层只负责让阅读路径更清楚。</p>
        <div class="hero-actions">
          <a class="primary-action" href="#docs">浏览 {len(docs)} 篇文档</a>
          <a class="secondary-action" href="README.html">从项目 README 开始</a>
        </div>
      </section>
      <section class="hero-card">
        <h2>活跃范围</h2>
        <p>包含 root、docs/confirmed、operational、docs/reference 和 kb 下的 Markdown；排除 docs/archive、archive 和构建产物目录。</p>
        <dl class="stat-grid">
          {render_count_stats(counts)}
        </dl>
      </section>
    </div>
  </header>

  <main>
    <section class="concept-strip" aria-label="RTS 核心心智模型">
      <article>
        <span>01</span>
        <h2>双核心</h2>
        <p>受控真相源原子能力与托管 LLM 分析服务并列存在。</p>
      </article>
      <article>
        <span>02</span>
        <h2>Truth Boundary</h2>
        <p>事实回到 L2、dependency、授权治理视图和 trace；LLM 输出不是 truth owner。</p>
      </article>
      <article>
        <span>03</span>
        <h2>Managed / Tool</h2>
        <p>内部 managed mode 与外部 tool mode 共享同一个 RTS service gate。</p>
      </article>
    </section>

    <section class="route-panel">
      <div>
        <p class="eyebrow">推荐阅读路线</p>
        <h2>先建立边界，再进入实现</h2>
        <p>如果只想快速了解项目，请从 README、confirmed README 和总纲开始；如果要运行或调用服务，直接看 runbook 与 API guide。</p>
      </div>
      <div class="route-list">
        {baseline_links}
      </div>
    </section>

    <section class="example-panel" id="examples">
      <div>
        <p class="eyebrow">Interactive Example</p>
        <h2>生成可复制的本地调用示例</h2>
        <p>选择入口和 sample scope，右侧会生成 curl。示例只帮助调用，不改变文档或服务状态。</p>
      </div>
      <div class="example-builder">
        <label>入口
          <select id="example-endpoint">
            <option value="query">/api/v1/query deterministic 查询</option>
            <option value="ask">/api/v1/ask managed analysis</option>
            <option value="scenario">/api/v1/scenario/analyze-failed-message</option>
            <option value="mcp">/mcp/tools 工具清单</option>
          </select>
        </label>
        <label>Scope
          <select id="example-scope">
            <option value="photo">当前默认 photo NDF cutoff scope</option>
            <option value="payments">回滚 sample payments scope</option>
          </select>
        </label>
        <pre class="example-output"><code id="example-output"></code></pre>
        <button class="copy-example" type="button" data-copy-example>复制示例</button>
      </div>
    </section>

    <section class="docs-panel" id="docs">
      <div class="docs-toolbar">
        <div>
          <p class="eyebrow">Document Library</p>
          <h2>活跃 Markdown 文档</h2>
        </div>
        <label class="search-box">
          <span>搜索</span>
          <input type="search" data-doc-search placeholder="输入标题、路径、summary 或分类">
        </label>
      </div>
      <div class="filter-row">
        <button class="filter-pill active" type="button" data-filter="all">全部 <span>{len(docs)}</span></button>
        {category_buttons}
      </div>
      <div class="doc-grid" data-doc-grid>
        {cards}
      </div>
      <p class="empty-state" data-empty-state hidden>没有匹配的文档。</p>
    </section>
  </main>

  <footer class="site-footer">
    <p>Generated from active Markdown at {esc(generated)} by <code>tools/build_html_docs.py</code>.</p>
  </footer>
  <script src="assets/search-index.js"></script>
  <script src="assets/app.js"></script>
</body>
</html>
"""
    index_path.write_text(body, encoding="utf-8")


def category_counts(docs: list[Doc]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for doc in docs:
        counts[doc.category] = counts.get(doc.category, 0) + 1
    return dict(sorted(counts.items(), key=lambda item: CATEGORY_RANK.get(item[0], 99)))


def render_count_stats(counts: dict[str, int]) -> str:
    return "\n".join(
        f"<div><dt>{esc(category)}</dt><dd>{count}</dd></div>" for category, count in counts.items()
    )


def render_baseline_route(docs: list[Doc], index_path: Path) -> str:
    selected = [
        "docs/confirmed/project-alignment-summary-zh.md",
        "docs/confirmed/system-constitution-v1.md",
        "docs/confirmed/kb-to-index-projection-contract-zh.md",
        "docs/confirmed/llm-harness-and-agent-integration-alignment-zh.md",
        "docs/confirmed/internal-llm-agent-service-implementation-plan-zh.md",
        "docs/java-service-runbook-zh.md",
        "docs/api-caller-guide-zh.md",
    ]
    docs_by_rel = {doc.rel_path: doc for doc in docs}
    links = []
    for index, rel_path in enumerate(selected, start=1):
        doc = docs_by_rel.get(rel_path)
        if not doc:
            continue
        href = rel_url(index_path, doc.output_path)
        links.append(
            f"""<a class="route-item" href="{href}">
              <span>{index:02d}</span>
              <strong>{esc(doc.title)}</strong>
              <em>{esc(doc.category)}</em>
            </a>"""
        )
    return "\n".join(links)


def render_doc_card(doc: Doc, index_path: Path) -> str:
    href = rel_url(index_path, doc.output_path)
    search_text = " ".join([doc.title, doc.summary, doc.rel_path, doc.category]).lower()
    return f"""<article class="doc-card" data-category="{esc(doc.category)}" data-search="{esc(search_text)}">
      <a href="{href}">
        <div class="card-topline">
          <span class="category-badge">{esc(doc.category)}</span>
          <code>{esc(doc.rel_path)}</code>
        </div>
        <h3>{esc(doc.title)}</h3>
        <p>{esc(doc.summary)}</p>
      </a>
    </article>"""


def write_assets(docs: list[Doc]) -> None:
    (ASSETS / "styles.css").write_text(STYLES, encoding="utf-8")
    (ASSETS / "app.js").write_text(APP_JS, encoding="utf-8")
    docs_payload = [
        {
            "title": doc.title,
            "path": doc.rel_path,
            "category": doc.category,
            "summary": doc.summary,
            "url": rel_url(OUT / "index.html", doc.output_path),
        }
        for doc in docs
    ]
    (ASSETS / "search-index.js").write_text(
        "window.RTS_DOCS = " + json.dumps(docs_payload, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )


def esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


STYLES = r"""
:root {
  color-scheme: light;
  --bg: #f6f0e5;
  --bg-strong: #ede1d0;
  --paper: #fffdf8;
  --paper-soft: #fbf6ed;
  --ink: #18231f;
  --muted: #64716a;
  --line: #dfd4c3;
  --accent: #0f766e;
  --accent-dark: #0b4f4b;
  --accent-soft: #d8eee8;
  --gold: #bb741f;
  --rust: #9b4d23;
  --shadow: 0 20px 60px rgba(55, 44, 28, .12);
  --radius-lg: 28px;
  --radius-md: 18px;
  --radius-sm: 12px;
  --content: min(1180px, calc(100vw - 40px));
  font-family: "Source Han Sans SC", "Noto Sans CJK SC", "PingFang SC", "Avenir Next", sans-serif;
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background:
    radial-gradient(circle at 14% 10%, rgba(15, 118, 110, .15), transparent 32%),
    radial-gradient(circle at 88% 4%, rgba(187, 116, 31, .16), transparent 28%),
    linear-gradient(135deg, var(--bg), #fbf8ef 52%, #f1e8d9);
  color: var(--ink);
  line-height: 1.65;
}

a {
  color: var(--accent-dark);
  text-decoration-thickness: .08em;
  text-underline-offset: .18em;
}

code,
pre,
kbd {
  font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace;
}

.skip-link {
  position: absolute;
  left: 16px;
  top: -80px;
  z-index: 30;
  padding: 10px 14px;
  border-radius: 999px;
  background: var(--ink);
  color: white;
  transition: top .2s ease;
}

.skip-link:focus {
  top: 12px;
}

.brand {
  display: inline-flex;
  align-items: center;
  gap: 10px;
  font-weight: 900;
  letter-spacing: .02em;
  text-decoration: none;
  color: var(--ink);
}

.brand::before {
  content: "";
  width: 16px;
  height: 16px;
  border-radius: 5px;
  background: linear-gradient(135deg, var(--accent), var(--gold));
  box-shadow: 0 0 0 5px rgba(15, 118, 110, .12);
}

.topbar,
.hero-nav {
  width: var(--content);
  margin: 0 auto;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 18px;
}

.topbar {
  position: sticky;
  top: 0;
  z-index: 20;
  padding: 14px 0;
  backdrop-filter: blur(18px);
}

.topnav,
.hero-nav {
  font-size: .94rem;
}

.topnav,
.hero-nav {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 14px;
}

.topnav a,
.hero-nav a {
  color: var(--ink);
  text-decoration: none;
  opacity: .82;
}

.home-hero {
  padding: 22px 0 38px;
}

.hero-grid {
  width: var(--content);
  margin: 56px auto 0;
  display: grid;
  grid-template-columns: minmax(0, 1.4fr) minmax(320px, .7fr);
  gap: 28px;
  align-items: stretch;
}

.eyebrow {
  margin: 0 0 10px;
  color: var(--rust);
  text-transform: uppercase;
  letter-spacing: .14em;
  font-size: .72rem;
  font-weight: 900;
}

h1,
h2,
h3 {
  line-height: 1.15;
}

.home-hero h1 {
  max-width: 900px;
  margin: 0;
  font-size: clamp(2.7rem, 7vw, 6.6rem);
  letter-spacing: -.07em;
}

.hero-lede {
  max-width: 760px;
  margin: 24px 0 0;
  font-size: clamp(1.1rem, 2vw, 1.45rem);
  color: #33413b;
}

.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 30px;
}

.primary-action,
.secondary-action {
  display: inline-flex;
  min-height: 46px;
  align-items: center;
  justify-content: center;
  padding: 12px 18px;
  border-radius: 999px;
  text-decoration: none;
  font-weight: 800;
}

.primary-action {
  background: var(--ink);
  color: #fffdf8;
  box-shadow: 0 14px 30px rgba(24, 35, 31, .18);
}

.secondary-action {
  border: 1px solid var(--line);
  background: rgba(255, 253, 248, .7);
  color: var(--ink);
}

.hero-card,
.route-panel,
.example-panel,
.docs-panel,
.concept-strip article,
.sidebar-card,
.doc-content,
.source-note {
  border: 1px solid rgba(117, 97, 66, .18);
  background: rgba(255, 253, 248, .82);
  box-shadow: var(--shadow);
  backdrop-filter: blur(12px);
}

.hero-card {
  border-radius: var(--radius-lg);
  padding: 28px;
}

.hero-card h2 {
  margin: 0 0 10px;
  font-size: 1.55rem;
}

.stat-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
  margin: 22px 0 0;
}

.stat-grid div {
  padding: 14px;
  border-radius: var(--radius-sm);
  background: var(--paper-soft);
}

.stat-grid dt {
  color: var(--muted);
  font-size: .78rem;
}

.stat-grid dd {
  margin: 4px 0 0;
  font-size: 1.6rem;
  font-weight: 900;
}

main {
  width: var(--content);
  margin: 0 auto;
}

.concept-strip {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 18px;
  margin: 24px 0;
}

.concept-strip article {
  border-radius: var(--radius-lg);
  padding: 24px;
}

.concept-strip span {
  display: inline-flex;
  width: 42px;
  height: 42px;
  align-items: center;
  justify-content: center;
  border-radius: 14px;
  background: var(--accent-soft);
  color: var(--accent-dark);
  font-weight: 900;
}

.concept-strip h2 {
  margin: 18px 0 8px;
}

.route-panel,
.example-panel {
  display: grid;
  grid-template-columns: minmax(260px, .75fr) minmax(0, 1.25fr);
  gap: 24px;
  margin: 22px 0;
  border-radius: var(--radius-lg);
  padding: 26px;
}

.route-panel h2,
.example-panel h2,
.docs-panel h2 {
  margin: 0;
  font-size: clamp(1.7rem, 3vw, 2.6rem);
  letter-spacing: -.04em;
}

.route-list {
  display: grid;
  gap: 10px;
}

.route-item {
  display: grid;
  grid-template-columns: 48px 1fr auto;
  align-items: center;
  gap: 14px;
  padding: 12px 14px;
  border-radius: var(--radius-md);
  background: var(--paper-soft);
  text-decoration: none;
  color: var(--ink);
}

.route-item span {
  color: var(--gold);
  font-weight: 900;
}

.route-item em {
  color: var(--muted);
  font-size: .82rem;
  font-style: normal;
}

.example-builder {
  display: grid;
  gap: 12px;
}

.example-builder label,
.search-box {
  display: grid;
  gap: 6px;
  color: var(--muted);
  font-size: .86rem;
  font-weight: 800;
}

select,
input[type="search"] {
  width: 100%;
  min-height: 44px;
  border: 1px solid var(--line);
  border-radius: 14px;
  background: var(--paper);
  color: var(--ink);
  padding: 10px 12px;
  font: inherit;
}

.example-output {
  min-height: 220px;
  margin: 0;
}

.copy-example,
.copy-code {
  border: 0;
  border-radius: 999px;
  background: var(--accent-dark);
  color: white;
  cursor: pointer;
  font-weight: 800;
}

.copy-example {
  justify-self: start;
  padding: 10px 15px;
}

.docs-panel {
  margin: 22px 0 42px;
  border-radius: var(--radius-lg);
  padding: 26px;
}

.docs-toolbar {
  display: grid;
  grid-template-columns: 1fr minmax(260px, 420px);
  gap: 20px;
  align-items: end;
}

.filter-row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin: 22px 0;
}

.filter-pill {
  border: 1px solid var(--line);
  border-radius: 999px;
  background: var(--paper-soft);
  color: var(--ink);
  cursor: pointer;
  padding: 8px 13px;
  font-weight: 800;
}

.filter-pill.active {
  background: var(--ink);
  color: white;
  border-color: var(--ink);
}

.filter-pill span {
  opacity: .7;
}

.doc-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}

.doc-card a {
  display: block;
  height: 100%;
  padding: 18px;
  border: 1px solid var(--line);
  border-radius: var(--radius-md);
  background: var(--paper);
  color: var(--ink);
  text-decoration: none;
  transition: transform .18s ease, box-shadow .18s ease, border-color .18s ease;
}

.doc-card a:hover {
  transform: translateY(-3px);
  border-color: rgba(15, 118, 110, .45);
  box-shadow: 0 18px 36px rgba(36, 51, 45, .12);
}

.card-topline {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  align-items: center;
}

.category-badge,
.chip {
  display: inline-flex;
  align-items: center;
  min-height: 26px;
  padding: 4px 9px;
  border-radius: 999px;
  background: var(--accent-soft);
  color: var(--accent-dark);
  font-size: .75rem;
  font-weight: 900;
}

.chip.subtle {
  background: var(--paper-soft);
  color: var(--muted);
}

.doc-card code {
  color: var(--muted);
  font-size: .72rem;
  word-break: break-all;
}

.doc-card h3 {
  margin: 16px 0 8px;
  font-size: 1.1rem;
}

.doc-card p {
  margin: 0;
  color: var(--muted);
  font-size: .92rem;
}

.empty-state,
.empty-note {
  color: var(--muted);
}

.site-footer {
  width: var(--content);
  margin: 0 auto;
  padding: 24px 0 44px;
  color: var(--muted);
}

.doc-shell {
  width: var(--content);
  margin: 14px auto 48px;
  display: grid;
  grid-template-columns: 320px minmax(0, 1fr);
  gap: 22px;
  align-items: start;
}

.doc-sidebar {
  position: sticky;
  top: 72px;
  display: grid;
  gap: 14px;
  max-height: calc(100vh - 92px);
  overflow: auto;
  padding-right: 4px;
}

.sidebar-card {
  border-radius: var(--radius-md);
  padding: 18px;
}

.sidebar-card h2 {
  margin: 0 0 8px;
  font-size: 1.1rem;
}

.sidebar-card h3 {
  margin: 16px 0 7px;
  font-size: .92rem;
}

.sidebar-card p,
.sidebar-card li {
  color: var(--muted);
  font-size: .9rem;
}

.sidebar-card ul {
  padding-left: 18px;
}

.chip-row {
  display: flex;
  flex-wrap: wrap;
  gap: 7px;
}

.toc-card ul {
  list-style: none;
  padding-left: 0;
  margin: 0;
}

.toc-card li {
  margin: 7px 0;
}

.toc-card a {
  text-decoration: none;
}

.mini-nav {
  display: grid;
  gap: 7px;
}

.mini-link {
  padding: 8px 10px;
  border-radius: 12px;
  color: var(--ink);
  text-decoration: none;
  background: var(--paper-soft);
  font-size: .88rem;
}

.mini-link.active {
  background: var(--ink);
  color: white;
}

.doc-content {
  border-radius: var(--radius-lg);
  padding: 0;
  overflow: hidden;
}

.doc-hero {
  padding: 34px 38px;
  background:
    linear-gradient(135deg, rgba(15, 118, 110, .12), rgba(187, 116, 31, .1)),
    var(--paper-soft);
  border-bottom: 1px solid var(--line);
}

.doc-hero h1 {
  margin: 0;
  font-size: clamp(2rem, 4vw, 4rem);
  letter-spacing: -.055em;
}

.doc-hero p:last-child {
  max-width: 820px;
  color: #3a463f;
  font-size: 1.08rem;
}

.source-note {
  margin: 24px 38px 0;
  padding: 14px 16px;
  border-radius: var(--radius-md);
  background: #fff8e8;
  color: #5d4224;
  box-shadow: none;
}

.markdown-body {
  padding: 22px 38px 44px;
  max-width: 920px;
}

.markdown-body h1 {
  display: none;
}

.markdown-body h2 {
  margin-top: 44px;
  padding-top: 8px;
  border-top: 1px solid var(--line);
  font-size: 1.85rem;
  letter-spacing: -.035em;
}

.markdown-body h3 {
  margin-top: 30px;
  font-size: 1.32rem;
}

.markdown-body h4 {
  margin-top: 24px;
  font-size: 1.08rem;
}

.markdown-body p,
.markdown-body li {
  color: #2e3934;
}

.markdown-body blockquote {
  margin: 20px 0;
  padding: 16px 18px;
  border-left: 5px solid var(--accent);
  border-radius: 0 var(--radius-md) var(--radius-md) 0;
  background: #eef8f4;
}

.markdown-body table {
  display: block;
  width: 100%;
  overflow-x: auto;
  border-collapse: collapse;
  margin: 18px 0;
}

.markdown-body th,
.markdown-body td {
  padding: 10px 12px;
  border: 1px solid var(--line);
  vertical-align: top;
}

.markdown-body th {
  background: var(--paper-soft);
  text-align: left;
}

.markdown-body pre {
  position: relative;
  overflow: auto;
  border-radius: 18px;
  padding: 18px;
  background: #17211d;
  color: #edf7ef;
  box-shadow: inset 0 0 0 1px rgba(255, 255, 255, .06);
}

.markdown-body :not(pre) > code,
.source-note code,
.site-footer code {
  padding: .13em .38em;
  border-radius: 7px;
  background: rgba(15, 118, 110, .1);
  color: var(--accent-dark);
}

.missing-link {
  padding: .1em .34em;
  border-radius: 7px;
  background: #f8e8d6;
  color: #8f3f1d;
  cursor: help;
}

.copy-code {
  position: absolute;
  top: 10px;
  right: 10px;
  padding: 6px 10px;
  opacity: 0;
  transition: opacity .18s ease;
}

pre:hover .copy-code,
pre:focus-within .copy-code {
  opacity: 1;
}

.markdown-body img {
  max-width: 100%;
  border-radius: var(--radius-md);
}

@media (max-width: 980px) {
  :root {
    --content: min(100vw - 24px, 760px);
  }

  .hero-grid,
  .route-panel,
  .example-panel,
  .doc-shell,
  .docs-toolbar {
    grid-template-columns: 1fr;
  }

  .concept-strip,
  .doc-grid {
    grid-template-columns: 1fr;
  }

  .doc-sidebar {
    position: static;
    max-height: none;
  }

  .markdown-body,
  .doc-hero {
    padding-left: 22px;
    padding-right: 22px;
  }

  .source-note {
    margin-left: 22px;
    margin-right: 22px;
  }
}
"""


APP_JS = r"""
(function () {
  const searchInput = document.querySelector("[data-doc-search]");
  const filterButtons = Array.from(document.querySelectorAll("[data-filter]"));
  const cards = Array.from(document.querySelectorAll(".doc-card"));
  const emptyState = document.querySelector("[data-empty-state]");
  let activeFilter = "all";

  function applyDocFilter() {
    if (!cards.length) return;
    const query = (searchInput && searchInput.value ? searchInput.value : "").trim().toLowerCase();
    let visible = 0;

    cards.forEach((card) => {
      const category = card.dataset.category || "";
      const search = card.dataset.search || "";
      const matchesFilter = activeFilter === "all" || category === activeFilter;
      const matchesSearch = !query || search.includes(query);
      const show = matchesFilter && matchesSearch;
      card.hidden = !show;
      if (show) visible += 1;
    });

    if (emptyState) emptyState.hidden = visible !== 0;
  }

  filterButtons.forEach((button) => {
    button.addEventListener("click", () => {
      activeFilter = button.dataset.filter || "all";
      filterButtons.forEach((item) => item.classList.toggle("active", item === button));
      applyDocFilter();
    });
  });

  if (searchInput) {
    searchInput.addEventListener("input", applyDocFilter);
  }

  document.querySelectorAll("pre").forEach((pre) => {
    if (pre.querySelector(".copy-code")) return;
    const button = document.createElement("button");
    button.className = "copy-code";
    button.type = "button";
    button.textContent = "复制";
    button.addEventListener("click", async () => {
      const text = pre.innerText.replace(/^复制\s*/, "");
      try {
        await navigator.clipboard.writeText(text);
        button.textContent = "已复制";
        setTimeout(() => (button.textContent = "复制"), 1200);
      } catch (error) {
        button.textContent = "复制失败";
        setTimeout(() => (button.textContent = "复制"), 1200);
      }
    });
    pre.appendChild(button);
  });

  const endpoint = document.getElementById("example-endpoint");
  const scope = document.getElementById("example-scope");
  const output = document.getElementById("example-output");
  const copyExample = document.querySelector("[data-copy-example]");

  const scopes = {
    photo: {
      query: "fixing time 怎么生成？",
      input: "Failed message mentions fixing time cutoff and NDF settlement.",
      channel: "tradition",
      product: "stella",
      pack: "fxd-ndf-cutoff-fixing",
      domain: "cutoff-fixing"
    },
    payments: {
      query: "payment amount 怎么生成？",
      input: "src.amount=123.45\nsrc.currency=USD",
      channel: "tradition",
      product: "stella",
      pack: "payments",
      domain: "core"
    }
  };

  function scopeJson(selected) {
    return `{
      "channel": "${selected.channel}",
      "product": "${selected.product}",
      "pack": "${selected.pack}",
      "domain": "${selected.domain}"
    }`;
  }

  function buildExample() {
    if (!endpoint || !scope || !output) return;
    const selectedScope = scopes[scope.value] || scopes.photo;
    const endpointValue = endpoint.value;

    if (endpointValue === "mcp") {
      output.textContent = "curl -s http://localhost:8080/mcp/tools | jq";
      return;
    }

    if (endpointValue === "scenario") {
      output.textContent = `curl -sS -X POST http://localhost:8080/api/v1/scenario/analyze-failed-message \\
  -H 'Content-Type: application/json' \\
  -H 'X-RTS-API-Key: tester-key' \\
  -d '{
    "input": "${selectedScope.input.replace(/\n/g, "\\n")}",
    "caller_id": "tester",
    "scope": ${scopeJson(selectedScope)},
    "output_mode": "default",
    "max_objects": 5
  }' | jq`;
      return;
    }

    const path = endpointValue === "ask" ? "/api/v1/ask" : "/api/v1/query";
    const llmFlag = endpointValue === "ask" ? "true" : "false";
    output.textContent = `curl -sS -X POST http://localhost:8080${path} \\
  -H 'Content-Type: application/json' \\
  -H 'X-RTS-API-Key: tester-key' \\
  -d '{
    "query": "${selectedScope.query}",
    "caller_id": "tester",
    "scope_hint": ${scopeJson(selectedScope)},
    "output_mode": "default",
    "use_llm": ${llmFlag}
  }' | jq`;
  }

  if (endpoint && scope && output) {
    endpoint.addEventListener("change", buildExample);
    scope.addEventListener("change", buildExample);
    buildExample();
  }

  if (copyExample && output) {
    copyExample.addEventListener("click", async () => {
      try {
        await navigator.clipboard.writeText(output.textContent || "");
        copyExample.textContent = "已复制";
        setTimeout(() => (copyExample.textContent = "复制示例"), 1200);
      } catch (error) {
        copyExample.textContent = "复制失败";
        setTimeout(() => (copyExample.textContent = "复制示例"), 1200);
      }
    });
  }
})();
"""


def build_experience_site() -> None:
    docs = load_docs()
    docs_by_rel = {doc.rel_path: doc for doc in docs}

    prepare_output_dir()
    for doc in docs:
        render_markdown_doc(doc, docs_by_rel)

    write_experience_assets(docs)
    write_experience_home(docs)
    write_experience_topic_pages(docs, docs_by_rel)
    for doc in docs:
        write_experience_doc_page(doc, docs, docs_by_rel)

    MARKER.write_text("generated by tools/build_html_docs.py\n", encoding="utf-8")
    print(f"Generated experience site with {len(docs)} source documents under {OUT.relative_to(ROOT)}")


def write_experience_assets(docs: list[Doc]) -> None:
    (ASSETS / "styles.css").write_text(EXPERIENCE_STYLES, encoding="utf-8")
    (ASSETS / "app.js").write_text(EXPERIENCE_JS, encoding="utf-8")
    docs_payload = [
        {
            "title": doc.title,
            "path": doc.rel_path,
            "category": doc.category,
            "summary": doc.summary,
            "url": rel_url(OUT / "index.html", doc.output_path),
        }
        for doc in docs
    ]
    (ASSETS / "search-index.js").write_text(
        "window.RTS_DOCS = " + json.dumps(docs_payload, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )


def site_nav(current: str = "") -> str:
    items = [
        ("index.html", "首页", "home"),
        ("start-here.html", "三分钟读懂", "start"),
        ("architecture.html", "架构边界", "architecture"),
        ("operations.html", "运行与调用", "operations"),
        ("roadmap.html", "路线图", "roadmap"),
        ("library.html", "来源文档", "library"),
    ]
    links = []
    for href, label, key in items:
        active = " active" if key == current else ""
        links.append(f'<a class="nav-link{active}" href="{href}">{esc(label)}</a>')
    return "\n".join(links)


def source_link(doc: Doc, from_file: Path) -> str:
    return rel_url(from_file, doc.output_path)


def find_doc(docs_by_rel: dict[str, Doc], rel_path: str) -> Doc | None:
    return docs_by_rel.get(rel_path)


def doc_href(docs_by_rel: dict[str, Doc], rel_path: str, from_file: Path) -> str:
    doc = find_doc(docs_by_rel, rel_path)
    if not doc:
        return "#"
    return rel_url(from_file, doc.output_path)


def write_experience_home(docs: list[Doc]) -> None:
    index_path = OUT / "index.html"
    docs_by_rel = {doc.rel_path: doc for doc in docs}
    doc_cards = "\n".join(render_experience_doc_card(doc, index_path) for doc in docs)
    generated = datetime.now().strftime("%Y-%m-%d %H:%M")
    body = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RTS 可读体验站</title>
  <link rel="stylesheet" href="assets/styles.css">
</head>
<body>
  <header class="site-header">
    <a class="brand-mark" href="index.html">RTS</a>
    <nav class="site-nav" aria-label="主导航">
      {site_nav("home")}
    </nav>
  </header>

  <main>
    <section class="hero-stage">
      <div class="hero-copy">
        <p class="kicker">Rule Truth Source · Transformation Rule System</p>
        <h1>读懂 RTS：<br>从规则文档到可信服务。</h1>
        <p class="hero-text">RTS 是面向银行报文转换的双核心规则真相服务：一边提供受控真相源原子能力，一边提供托管 LLM agent 分析能力。这个 HTML 站点不再搬运 Markdown，而是把活跃文档重组为更容易进入、理解和使用的阅读体验。</p>
        <div class="hero-actions">
          <a class="button primary" href="start-here.html">先用三分钟读懂</a>
          <a class="button secondary" href="architecture.html">看架构边界</a>
        </div>
      </div>
      <div class="truth-orbit" aria-label="RTS 双核心模型">
        <div class="orbit-card core">
          <span>RTS</span>
          <strong>service gates and proves</strong>
        </div>
        <div class="orbit-card truth">
          <span>Truth core</span>
          <p>L2 / dependency / release / trace</p>
        </div>
        <div class="orbit-card agent">
          <span>Analysis core</span>
          <p>managed LLM / scenario / tool mode</p>
        </div>
      </div>
    </section>

    <section class="reader-paths">
      <div class="section-heading">
        <p class="kicker">Choose Your Path</p>
        <h2>你现在想解决什么问题？</h2>
      </div>
      <div class="path-grid">
        <a class="path-card large" href="start-here.html">
          <span>01</span>
          <h3>第一次进入项目</h3>
          <p>先建立 RTS 不是 RAG、不是普通聊天机器人、也不是单一 SDK 包装的心智模型。</p>
        </a>
        <a class="path-card" href="architecture.html">
          <span>02</span>
          <h3>我要判断边界</h3>
          <p>看 truth owner、runtime projection、service gate、LLM 和 agent 的分工。</p>
        </a>
        <a class="path-card" href="operations.html">
          <span>03</span>
          <h3>我要跑起来或调用</h3>
          <p>直接进入本地启动、sample scope、query/ask/scenario/MCP 调用示例。</p>
        </a>
        <a class="path-card" href="roadmap.html">
          <span>04</span>
          <h3>我要看实现顺序</h3>
          <p>理解 Day1、Day2、internal agent 和最终路线图之间的关系。</p>
        </a>
      </div>
    </section>

    <section class="story-panel">
      <div class="section-heading">
        <p class="kicker">The Story</p>
        <h2>RTS 的核心不是“把规则放进 AI 问答”。</h2>
        <p>它的目标是让规则从 source material 走到可治理、可追溯、可审查、可查询、可解释的服务真相。</p>
      </div>
      <div class="flow-line">
        <article>
          <span>Source</span>
          <h3>多源材料</h3>
          <p>业务文档、Java/XSLT、Excel mapping、lookup、示例和 reviewer clarification。</p>
        </article>
        <article>
          <span>Govern</span>
          <h3>AI-first review</h3>
          <p>AI 做结构校验、冲突发现、证据整理和问题简化；人工做最终裁决。</p>
        </article>
        <article>
          <span>Publish</span>
          <h3>Runtime projection</h3>
          <p>approved truth 被发布成服务可读取的 projection，而不是直接读工作区文档。</p>
        </article>
        <article>
          <span>Serve</span>
          <h3>API / MCP / Ask</h3>
          <p>所有调用都经过 release、scope、permission、L2 hash、grounding、trace gate。</p>
        </article>
      </div>
    </section>

    <section class="mode-panel">
      <div class="mode-copy">
        <p class="kicker">Dual Core</p>
        <h2>两个核心能力，不是主次关系。</h2>
        <p>确定性能力是第一等公民，托管 LLM 分析也是第一等公民。LLM 不拥有 truth，但它是 RTS 正常产品形态中的受控分析与表达层。</p>
      </div>
      <div class="mode-grid">
        <article>
          <h3>受控真相源原子能力</h3>
          <p>query、find、read L2、dependency、trace、scope/navigation、grounding check。</p>
          <a href="architecture.html#atomic-capabilities">看原子能力</a>
        </article>
        <article>
          <h3>托管 LLM agent 分析</h3>
          <p>/ask、PR diff、exception、failed message、test planning、governance review。</p>
          <a href="architecture.html#managed-analysis">看 managed mode</a>
        </article>
      </div>
    </section>

    <section class="proof-panel">
      <div>
        <p class="kicker">Start From Sources</p>
        <h2>想核对原文？每个主题都能回到来源。</h2>
        <p>体验页负责重组表达；文档页负责保留完整原文和 docmeta。你可以先读策展内容，再展开完整 Markdown 来源。</p>
      </div>
      <div class="source-picks">
        <a href="{doc_href(docs_by_rel, "docs/confirmed/project-alignment-summary-zh.md", index_path)}">项目总纲</a>
        <a href="{doc_href(docs_by_rel, "docs/confirmed/system-constitution-v1.md", index_path)}">Constitution</a>
        <a href="{doc_href(docs_by_rel, "docs/confirmed/kb-to-index-projection-contract-zh.md", index_path)}">Projection Contract</a>
        <a href="{doc_href(docs_by_rel, "docs/api-caller-guide-zh.md", index_path)}">API Guide</a>
      </div>
    </section>

    <section class="library-preview" id="library">
      <div class="docs-toolbar">
        <div>
          <p class="kicker">Source Library</p>
          <h2>活跃来源文档</h2>
          <p>这里是来源索引，不再是默认阅读入口。需要核对细节时再进入。</p>
        </div>
        <label class="search-box">
          <span>搜索来源</span>
          <input type="search" data-doc-search placeholder="搜索标题、路径、summary 或分类">
        </label>
      </div>
      <div class="doc-grid" data-doc-grid>
        {doc_cards}
      </div>
      <p class="empty-state" data-empty-state hidden>没有匹配的来源文档。</p>
      <a class="button secondary" href="library.html">打开完整来源库</a>
    </section>
  </main>

  <footer class="site-footer">
    <p>从 {len(docs)} 篇非归档 Markdown 生成。更新时间：{esc(generated)}。原文不被改写，阅读体验由 HTML 层重新组织。</p>
  </footer>
  <script src="assets/search-index.js"></script>
  <script src="assets/app.js"></script>
</body>
</html>
"""
    index_path.write_text(body, encoding="utf-8")


def write_experience_topic_pages(docs: list[Doc], docs_by_rel: dict[str, Doc]) -> None:
    write_start_page(docs, docs_by_rel)
    write_architecture_page(docs, docs_by_rel)
    write_operations_page(docs, docs_by_rel)
    write_roadmap_page(docs, docs_by_rel)
    write_library_page(docs)


def write_topic_shell(path: Path, key: str, title: str, lede: str, body_html: str) -> None:
    page = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)} | RTS</title>
  <link rel="stylesheet" href="assets/styles.css">
</head>
<body>
  <header class="site-header">
    <a class="brand-mark" href="index.html">RTS</a>
    <nav class="site-nav" aria-label="主导航">
      {site_nav(key)}
    </nav>
  </header>
  <main>
    <section class="page-hero">
      <p class="kicker">RTS Reading Experience</p>
      <h1>{esc(title)}</h1>
      <p>{esc(lede)}</p>
    </section>
    {body_html}
  </main>
  <footer class="site-footer">
    <p>策展页根据 confirmed / operational 文档重组表达；需要逐字核对时请进入来源文档页。</p>
  </footer>
  <script src="assets/search-index.js"></script>
  <script src="assets/app.js"></script>
</body>
</html>
"""
    path.write_text(page, encoding="utf-8")


def source_badges(items: list[tuple[str, str]], docs_by_rel: dict[str, Doc], from_file: Path) -> str:
    links = []
    for label, rel_path in items:
        href = doc_href(docs_by_rel, rel_path, from_file)
        links.append(f'<a href="{href}">{esc(label)}</a>')
    return "\n".join(links)


def write_start_page(docs: list[Doc], docs_by_rel: dict[str, Doc]) -> None:
    path = OUT / "start-here.html"
    body = f"""
    <section class="briefing-grid">
      <article class="briefing-card highlight">
        <span class="card-number">01</span>
        <h2>RTS 是规则真相服务，不是普通 RAG。</h2>
        <p>RTS 的核心职责是从多源材料形成 governed truth，再以 API、MCP、/ask 和 scenario endpoint 对外提供可追溯能力。</p>
      </article>
      <article class="briefing-card">
        <span class="card-number">02</span>
        <h2>LLM 是核心能力，但不是 truth owner。</h2>
        <p>LLM 做受控分析、冲突发现、影响候选、测试候选和表达；事实必须回到 L2、dependency、授权治理视图或 trace。</p>
      </article>
      <article class="briefing-card">
        <span class="card-number">03</span>
        <h2>candidate 边界不是能力上限。</h2>
        <p>场景服务可以做深入分析，但 impact/test/root cause 等输出必须区分 facts、inferences、unknowns、candidates 和 human decisions。</p>
      </article>
    </section>

    <section class="reading-lane">
      <div>
        <p class="kicker">Mental Model</p>
        <h2>先记住这五句话。</h2>
      </div>
      <ol class="big-list">
        <li><strong>KB owns truth</strong>：完整治理图在 KB，而不是搜索索引或聊天记录。</li>
        <li><strong>Projection serves truth</strong>：runtime projection 是 approved truth 的服务运行视图。</li>
        <li><strong>Service gates truth</strong>：RTS service 负责 release、scope、permission、hash、grounding、refusal、trace。</li>
        <li><strong>LLM analyzes truth</strong>：AI 可以分析和表达，但不能偷偷裁决事实。</li>
        <li><strong>Human decides conflict</strong>：材料冲突和关键歧义最终由人工 review/adjudication 记录。</li>
      </ol>
    </section>

    <section class="choice-panel" data-tabs>
      <div class="section-heading">
        <p class="kicker">Reader Modes</p>
        <h2>按你的角色进入。</h2>
      </div>
      <div class="tab-buttons" role="tablist">
        <button class="tab-button active" type="button" data-tab="business">业务/BA</button>
        <button class="tab-button" type="button" data-tab="developer">开发</button>
        <button class="tab-button" type="button" data-tab="agent">Agent 集成</button>
        <button class="tab-button" type="button" data-tab="reviewer">治理/Review</button>
      </div>
      <div class="tab-panel active" data-tab-panel="business">
        <h3>你要关心：答案是否有证据、scope 是否正确、unknown 是否被说清楚。</h3>
        <p>优先读项目总纲、Constitution 和 API guide。不要把 candidate 当 final business decision。</p>
      </div>
      <div class="tab-panel" data-tab-panel="developer">
        <h3>你要关心：projection、L2、dependency、trace 和 refusal 是否稳定。</h3>
        <p>优先读 projection contract、Day1 baseline、runbook 和 internal agent implementation plan。</p>
      </div>
      <div class="tab-panel" data-tab-panel="agent">
        <h3>你要关心：managed mode 与 tool mode 共享同一个 truth access boundary。</h3>
        <p>外部 agent 可以规划工作流，但每个 RTS tool call 仍要走 service gate。</p>
      </div>
      <div class="tab-panel" data-tab-panel="reviewer">
        <h3>你要关心：AI-first review 不是 AI-final decision。</h3>
        <p>AI 简化冲突、找证据、提问题；人工裁决和 signoff 才能进入 approved truth。</p>
      </div>
    </section>

    <section class="source-strip">
      <p class="kicker">主要来源</p>
      {source_badges([
          ("项目总纲", "docs/confirmed/project-alignment-summary-zh.md"),
          ("Constitution", "docs/confirmed/system-constitution-v1.md"),
          ("Confirmed README", "docs/confirmed/README.md"),
      ], docs_by_rel, path)}
    </section>
    """
    write_topic_shell(path, "start", "三分钟读懂 RTS", "先不读长文档，用一条清楚的故事建立 RTS 的核心心智模型。", body)


def write_architecture_page(docs: list[Doc], docs_by_rel: dict[str, Doc]) -> None:
    path = OUT / "architecture.html"
    body = f"""
    <section class="architecture-map">
      <div class="layer source">
        <span>01</span>
        <h2>Source Material</h2>
        <p>业务文档、代码、mapping、lookup、示例、clarification。</p>
      </div>
      <div class="layer govern">
        <span>02</span>
        <h2>Governed KB</h2>
        <p>Rule、Rule pack、Evidence chain、review、adjudication、signoff。</p>
      </div>
      <div class="layer projection">
        <span>03</span>
        <h2>Runtime Projection</h2>
        <p>release manifest、scope registry、object manifest、cards、L2、dependency。</p>
      </div>
      <div class="layer service">
        <span>04</span>
        <h2>RTS Service Gate</h2>
        <p>release、scope、permission、hash、grounding、refusal、trace。</p>
      </div>
      <div class="layer consume">
        <span>05</span>
        <h2>Consumption</h2>
        <p>query、ask、scenario、MCP、pipeline、external agent。</p>
      </div>
    </section>

    <section class="split-explain">
      <article id="atomic-capabilities">
        <p class="kicker">Core A</p>
        <h2>受控真相源原子能力</h2>
        <p>这些能力回答“能不能安全地找到和读取 truth material”。它们是 deterministic information service，不是 AI 不可用时才存在的 fallback。</p>
        <ul class="tag-list">
          <li>resolve scope</li>
          <li>find objects</li>
          <li>read object card</li>
          <li>read L2</li>
          <li>dependency traversal</li>
          <li>trace and grounding</li>
        </ul>
      </article>
      <article id="managed-analysis">
        <p class="kicker">Core B</p>
        <h2>托管 LLM agent 分析</h2>
        <p>这些能力回答“如何把 truth material 变成可用分析”。AI 可以规划、取证、表达 unknown 和 candidate，但不能拥有 truth authority。</p>
        <ul class="tag-list">
          <li>/ask</li>
          <li>PR diff impact</li>
          <li>exception investigation</li>
          <li>failed message analysis</li>
          <li>test planning</li>
          <li>governance review</li>
        </ul>
      </article>
    </section>

    <section class="boundary-table">
      <div>
        <p class="kicker">Boundary Checks</p>
        <h2>什么能支撑事实，什么不能。</h2>
      </div>
      <div class="table-card">
        <table>
          <thead><tr><th>材料</th><th>用途</th><th>是否拥有 truth</th></tr></thead>
          <tbody>
            <tr><td>L2 runtime object</td><td>事实回答、诊断、测试规划 grounding</td><td>可以支撑事实</td></tr>
            <tr><td>dependency edge</td><td>解释、影响候选、必要上下文加载</td><td>可以支撑依赖事实</td></tr>
            <tr><td>object card / L0 / L1</td><td>导航、消歧、召回</td><td>不能替代 L2</td></tr>
            <tr><td>LLM draft</td><td>分析草稿、表达、候选</td><td>不能自行成为 truth</td></tr>
            <tr><td>memory / trace feedback</td><td>体验和检索辅助</td><td>不能参与 truth validation</td></tr>
          </tbody>
        </table>
      </div>
    </section>

    <section class="source-strip">
      <p class="kicker">主要来源</p>
      {source_badges([
          ("Projection Contract", "docs/confirmed/kb-to-index-projection-contract-zh.md"),
          ("LLM Alignment", "docs/confirmed/llm-harness-and-agent-integration-alignment-zh.md"),
          ("Internal Agent Plan", "docs/confirmed/internal-llm-agent-service-implementation-plan-zh.md"),
      ], docs_by_rel, path)}
    </section>
    """
    write_topic_shell(path, "architecture", "架构边界", "把 KB、projection、index、service、LLM 和 agent 的责任分清楚。", body)


def write_operations_page(docs: list[Doc], docs_by_rel: dict[str, Doc]) -> None:
    path = OUT / "operations.html"
    body = f"""
    <section class="run-cards">
      <article>
        <span class="card-number">01</span>
        <h2>本地启动</h2>
        <p>默认使用 sample runtime projection store。服务不直接读取 KB/candidate pack 作为 truth。</p>
        <pre><code>RTS_STORE_ROOT="$PWD/sample-projection/runtime-store" \\
JAVA_HOME=$(/usr/libexec/java_home -v 17) \\
mvn spring-boot:run</code></pre>
      </article>
      <article>
        <span class="card-number">02</span>
        <h2>快速验证</h2>
        <p>先看 MCP 工具清单，再用当前 active release 的 photo scope 查询。</p>
        <pre><code>curl -s http://localhost:8080/mcp/tools | jq</code></pre>
      </article>
      <article>
        <span class="card-number">03</span>
        <h2>提交前检查</h2>
        <p>运行测试和 diff 检查，避免把运行配置或格式问题带进提交。</p>
        <pre><code>JAVA_HOME=$(/usr/libexec/java_home -v 17) mvn verify
git diff --check
git status --short</code></pre>
      </article>
    </section>

    <section class="example-panel refined" id="examples">
      <div>
        <p class="kicker">Try It</p>
        <h2>选择场景，生成可复制请求。</h2>
        <p>这个示例生成器是为了降低调用门槛。它不会修改服务状态，也不会替代 API guide。</p>
      </div>
      <div class="example-builder">
        <label>入口
          <select id="example-endpoint">
            <option value="query">/api/v1/query deterministic 查询</option>
            <option value="ask">/api/v1/ask managed analysis</option>
            <option value="scenario">/api/v1/scenario/analyze-failed-message</option>
            <option value="mcp">/mcp/tools 工具清单</option>
          </select>
        </label>
        <label>Scope
          <select id="example-scope">
            <option value="photo">当前默认 photo NDF cutoff scope</option>
            <option value="payments">回滚 sample payments scope</option>
          </select>
        </label>
        <pre class="example-output"><code id="example-output"></code></pre>
        <button class="copy-example" type="button" data-copy-example>复制示例</button>
      </div>
    </section>

    <section class="warning-panel">
      <h2>调用时最容易踩的坑</h2>
      <ul class="big-list compact">
        <li><strong>scope 不完整</strong>：channel/product/pack/domain 必须属于当前 active release。</li>
        <li><strong>字段名写错</strong>：请求 body 使用 snake_case，不要用 camelCase。</li>
        <li><strong>LLM 不可用</strong>：/ask 会降级为结构化信息提供服务，不应被描述成等价 managed analysis。</li>
        <li><strong>candidate 被误用</strong>：scenario 输出不是 release approval、final root cause 或 QA signoff。</li>
      </ul>
    </section>

    <section class="source-strip">
      <p class="kicker">主要来源</p>
      {source_badges([
          ("Runbook", "docs/java-service-runbook-zh.md"),
          ("API Guide", "docs/api-caller-guide-zh.md"),
          ("Sample Commands", "docs/day1-sample-pack-test-commands.md"),
      ], docs_by_rel, path)}
    </section>
    """
    write_topic_shell(path, "operations", "运行与调用", "把启动、验证、API 调用和常见误区放在一条可执行路径里。", body)


def write_roadmap_page(docs: list[Doc], docs_by_rel: dict[str, Doc]) -> None:
    path = OUT / "roadmap.html"
    body = f"""
    <section class="timeline">
      <article>
        <span>Baseline</span>
        <h2>Constitution + Projection Contract</h2>
        <p>先锁住 truth ownership、runtime projection、refusal、permissioned governance view。</p>
      </article>
      <article>
        <span>Day1</span>
        <h2>Query / Tool Service + Controlled Harness</h2>
        <p>建立文件系统 store、Lucene、L2 read/hash、trace/refusal、REST/MCP 和第一版 /ask。</p>
      </article>
      <article>
        <span>Internal Agent</span>
        <h2>Service-owned Managed Loop</h2>
        <p>planner、orchestrator、context snapshot、claim validation、scenario compiler、evaluation gate。</p>
      </article>
      <article>
        <span>Day2</span>
        <h2>Controlled Agentic Retrieval</h2>
        <p>多步 retrieval、confusable、rerank、expanded MCP、impact/test candidate 和评估闭环。</p>
      </article>
      <article>
        <span>Final</span>
        <h2>LLM-agent-ready Rule Truth Service</h2>
        <p>managed mode 与 external tool mode 共享稳定原子能力和同一 truth access boundary。</p>
      </article>
    </section>

    <section class="decision-grid">
      <article>
        <h2>现在不该做什么</h2>
        <p>不要把 OpenSearch、vector、外部 agent SDK 或 memory 写成 truth core；它们最多是 adapter、检索增强或 workflow sidecar。</p>
      </article>
      <article>
        <h2>下一步真正重要什么</h2>
        <p>不是让模型更会说，而是让 managed analysis 在 /ask 和 scenario endpoint 中成为稳定正常态，同时 claim validation 和 trace 能证明它没有越界。</p>
      </article>
    </section>

    <section class="source-strip">
      <p class="kicker">主要来源</p>
      {source_badges([
          ("Day1", "docs/confirmed/day1-query-service-and-llm-harness-plan-zh.md"),
          ("Day2", "docs/confirmed/day2-agentic-retrieval-evolution-plan-zh.md"),
          ("Final Roadmap", "docs/confirmed/final-llm-agent-service-plan-zh.md"),
          ("Decision Register", "docs/confirmed/document-decision-register-zh.md"),
      ], docs_by_rel, path)}
    </section>
    """
    write_topic_shell(path, "roadmap", "路线图", "把 confirmed baseline、Day1、Day2、internal agent 和最终服务形态串成一条实现路径。", body)


def write_library_page(docs: list[Doc]) -> None:
    path = OUT / "library.html"
    cards = "\n".join(render_experience_doc_card(doc, path) for doc in docs)
    body = f"""
    <section class="library-preview full">
      <div class="docs-toolbar">
        <div>
          <p class="kicker">Source Library</p>
          <h2>所有活跃来源文档</h2>
          <p>这里保留完整来源入口。默认排除 archive；reference 只作 rationale，不覆盖 confirmed baseline。</p>
        </div>
        <label class="search-box">
          <span>搜索来源</span>
          <input type="search" data-doc-search placeholder="搜索标题、路径、summary 或分类">
        </label>
      </div>
      <div class="doc-grid" data-doc-grid>
        {cards}
      </div>
      <p class="empty-state" data-empty-state hidden>没有匹配的来源文档。</p>
    </section>
    """
    write_topic_shell(path, "library", "来源文档库", "当你需要逐字核对或继续开发时，从这里进入完整来源。", body)


def write_experience_doc_page(doc: Doc, docs: list[Doc], docs_by_rel: dict[str, Doc]) -> None:
    doc.output_path.parent.mkdir(parents=True, exist_ok=True)
    css_href = rel_url(doc.output_path, ASSETS / "styles.css")
    js_href = rel_url(doc.output_path, ASSETS / "app.js")
    home_href = rel_url(doc.output_path, OUT / "index.html")
    source_href = rel_url(doc.output_path, doc.source_path)
    insight_cards = render_doc_insights(doc)
    chapter_cards = render_chapter_cards(doc)
    meta_cards = render_doc_meta_cards(doc, docs_by_rel)
    related = render_related_sources(doc, docs, docs_by_rel)
    page_title = f"{doc.title} | RTS 来源解读"
    body = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(page_title)}</title>
  <link rel="stylesheet" href="{css_href}">
</head>
<body>
  <header class="site-header doc-local">
    <a class="brand-mark" href="{home_href}">RTS</a>
    <nav class="site-nav" aria-label="主导航">
      <a class="nav-link" href="{home_href}">首页</a>
      <a class="nav-link" href="{rel_url(doc.output_path, OUT / "start-here.html")}">三分钟读懂</a>
      <a class="nav-link" href="{rel_url(doc.output_path, OUT / "architecture.html")}">架构边界</a>
      <a class="nav-link" href="{rel_url(doc.output_path, OUT / "library.html")}">来源文档</a>
    </nav>
  </header>
  <main class="source-page">
    <section class="source-hero">
      <p class="kicker">{esc(doc.category)} · {esc(doc.rel_path)}</p>
      <h1>{esc(doc.title)}</h1>
      <p>{esc(doc.summary)}</p>
      <div class="hero-actions">
        <a class="button primary" href="#readable">先读解读版</a>
        <a class="button secondary" href="#source">展开完整原文</a>
        <a class="button ghost" href="{source_href}">Markdown 源文件</a>
      </div>
    </section>

    <section class="readable-layout" id="readable">
      <aside class="readable-aside">
        <div class="aside-card">
          <p class="kicker">How To Read</p>
          <h2>这不是原文搬运页</h2>
          <p>先读下面的摘要、关键章节和使用场景；需要严格核对时再打开完整原文。</p>
        </div>
        {meta_cards}
        {related}
      </aside>
      <div class="readable-main">
        <section class="insight-grid">
          {insight_cards}
        </section>
        <section class="chapter-section">
          <div class="section-heading">
            <p class="kicker">Readable Outline</p>
            <h2>这篇文档在讲什么</h2>
          </div>
          <div class="chapter-grid">
            {chapter_cards}
          </div>
        </section>
      </div>
    </section>

    <details class="source-drawer" id="source">
      <summary>
        <span>完整 Markdown 来源</span>
        <strong>用于核对事实、字段和原始措辞</strong>
      </summary>
      <div class="markdown-body">
        {doc.body_html}
      </div>
    </details>
  </main>
  <script src="{js_href}"></script>
</body>
</html>
"""
    doc.output_path.write_text(body, encoding="utf-8")


def render_doc_insights(doc: Doc) -> str:
    role = doc.meta.get("role") or doc.category
    layer = doc.meta.get("layer") or "active"
    intro = first_meaningful_sentences(doc.body_markdown, 2)
    if not intro:
        intro = doc.summary
    insights = [
        ("这篇的作用", doc.summary or "说明当前 RTS 活跃文档中的一个主题。"),
        ("先抓住", intro),
        ("权威层级", f"{doc.category} / role: {role} / layer: {layer}"),
    ]
    cards = []
    for title, text in insights:
        cards.append(f"""<article class="insight-card">
          <h2>{esc(title)}</h2>
          <p>{esc(text)}</p>
        </article>""")
    return "\n".join(cards)


def first_meaningful_sentences(markdown_text: str, count: int) -> str:
    plain = []
    in_code = False
    for line in markdown_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code = not in_code
            continue
        if in_code or not stripped or stripped.startswith(("#", "|", "```")):
            continue
        if stripped.startswith("- "):
            continue
        plain.append(strip_markdown_inline(stripped))
        if len(" ".join(plain)) > 220:
            break
    text = " ".join(plain)
    if not text:
        return ""
    pieces = re.split(r"(?<=[。.!?])\s+", text)
    return " ".join(pieces[:count]).strip()


def render_chapter_cards(doc: Doc) -> str:
    sections = extract_heading_sections(doc.body_markdown)
    if not sections:
        return '<article class="chapter-card"><h3>完整来源</h3><p>这篇文档没有明显章节，请直接展开完整 Markdown 来源核对。</p></article>'
    cards = []
    for title, excerpt in sections[:12]:
        cards.append(f"""<article class="chapter-card">
          <h3>{esc(title)}</h3>
          <p>{esc(excerpt or "这一节用于展开该主题的细节、边界或操作说明。")}</p>
        </article>""")
    return "\n".join(cards)


def extract_heading_sections(markdown_text: str) -> list[tuple[str, str]]:
    sections: list[tuple[str, list[str]]] = []
    current_title = ""
    current_lines: list[str] = []
    in_code = False
    for line in markdown_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        match = re.match(r"^##\s+(.+?)\s*$", stripped)
        if match:
            if current_title:
                sections.append((strip_markdown_inline(current_title), current_lines))
            current_title = match.group(1)
            current_lines = []
            continue
        if current_title and stripped and not stripped.startswith(("#", "|")):
            current_lines.append(stripped)
    if current_title:
        sections.append((strip_markdown_inline(current_title), current_lines))

    result: list[tuple[str, str]] = []
    for title, lines in sections:
        excerpt_lines = []
        for line in lines:
            if line.startswith("- "):
                excerpt_lines.append(strip_markdown_inline(line[2:]))
            elif not line.startswith(("```", ">")):
                excerpt_lines.append(strip_markdown_inline(line))
            if len(" ".join(excerpt_lines)) > 160:
                break
        result.append((title, " ".join(excerpt_lines)[:220]))
    return result


def render_doc_meta_cards(doc: Doc, docs_by_rel: dict[str, Doc]) -> str:
    blocks = []
    read_when = doc.meta.get("read_when")
    if read_when:
        blocks.append(render_compact_meta_block("适合阅读", read_when, docs_by_rel, doc.output_path))
    skip_when = doc.meta.get("skip_when")
    if skip_when:
        blocks.append(render_compact_meta_block("可跳过", skip_when, docs_by_rel, doc.output_path))
    return "\n".join(blocks)


def render_compact_meta_block(title: str, values: Any, docs_by_rel: dict[str, Doc], current_output: Path) -> str:
    if isinstance(values, str):
        values = [values]
    items = "\n".join(f"<li>{render_meta_value(str(item), docs_by_rel, current_output)}</li>" for item in values[:5])
    return f"""<div class="aside-card">
      <p class="kicker">{esc(title)}</p>
      <ul>{items}</ul>
    </div>"""


def render_related_sources(doc: Doc, docs: list[Doc], docs_by_rel: dict[str, Doc]) -> str:
    source_values = doc.meta.get("source_of_truth") or []
    if isinstance(source_values, str):
        source_values = [source_values]
    links = []
    for value in source_values[:6]:
        clean = str(value).strip().strip("`")
        target = docs_by_rel.get(clean)
        if target:
            href = rel_url(doc.output_path, target.output_path)
            links.append(f'<a href="{href}">{esc(target.title)}</a>')
    if not links:
        peers = [item for item in docs if item.category == doc.category and item.rel_path != doc.rel_path][:5]
        for peer in peers:
            links.append(f'<a href="{rel_url(doc.output_path, peer.output_path)}">{esc(peer.title)}</a>')
    if not links:
        return ""
    return f"""<div class="aside-card related-card">
      <p class="kicker">关联来源</p>
      {''.join(links)}
    </div>"""


def render_experience_doc_card(doc: Doc, from_file: Path) -> str:
    href = rel_url(from_file, doc.output_path)
    search_text = " ".join([doc.title, doc.summary, doc.rel_path, doc.category]).lower()
    return f"""<article class="source-card" data-category="{esc(doc.category)}" data-search="{esc(search_text)}">
      <a href="{href}">
        <span class="source-type">{esc(doc.category)}</span>
        <h3>{esc(doc.title)}</h3>
        <p>{esc(doc.summary)}</p>
        <code>{esc(doc.rel_path)}</code>
      </a>
    </article>"""


EXPERIENCE_STYLES = r"""
:root {
  --ink: #17211d;
  --muted: #68746e;
  --paper: #fffaf0;
  --paper-strong: #f5ead7;
  --canvas: #efe2ca;
  --line: rgba(72, 57, 37, .18);
  --green: #0d7069;
  --green-dark: #084a46;
  --green-soft: #d9eee8;
  --amber: #c58228;
  --clay: #994b26;
  --blue: #2a6478;
  --shadow: 0 24px 70px rgba(49, 38, 22, .16);
  --radius-xl: 36px;
  --radius-lg: 24px;
  --radius-md: 16px;
  --content: min(1180px, calc(100vw - 40px));
  font-family: "Source Han Sans SC", "Noto Sans CJK SC", "PingFang SC", "Avenir Next", sans-serif;
}

* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  color: var(--ink);
  background:
    radial-gradient(circle at 10% 0%, rgba(13, 112, 105, .22), transparent 28%),
    radial-gradient(circle at 95% 5%, rgba(197, 130, 40, .22), transparent 26%),
    linear-gradient(135deg, #f4ead8, #fff8e9 48%, #ead9bd);
  line-height: 1.65;
}

a { color: var(--green-dark); text-underline-offset: .18em; }
code, pre, kbd { font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace; }

.site-header {
  width: var(--content);
  margin: 0 auto;
  padding: 18px 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  position: sticky;
  top: 0;
  z-index: 20;
  backdrop-filter: blur(18px);
}

.brand-mark {
  width: 54px;
  height: 54px;
  border-radius: 18px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: var(--ink);
  color: var(--paper);
  text-decoration: none;
  font-weight: 950;
  letter-spacing: -.05em;
  box-shadow: var(--shadow);
}

.site-nav {
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-end;
  gap: 8px;
}

.nav-link {
  padding: 9px 12px;
  border-radius: 999px;
  color: var(--ink);
  text-decoration: none;
  font-size: .92rem;
  font-weight: 800;
  background: rgba(255, 250, 240, .48);
  border: 1px solid transparent;
}

.nav-link.active,
.nav-link:hover {
  border-color: var(--line);
  background: var(--paper);
}

main, .site-footer {
  width: var(--content);
  margin: 0 auto;
}

.hero-stage {
  min-height: calc(100vh - 96px);
  display: grid;
  grid-template-columns: minmax(0, 1.08fr) minmax(340px, .82fr);
  gap: 34px;
  align-items: center;
  padding: 42px 0 72px;
}

.kicker {
  margin: 0 0 12px;
  color: var(--clay);
  text-transform: uppercase;
  letter-spacing: .15em;
  font-size: .74rem;
  font-weight: 950;
}

h1, h2, h3 { line-height: 1.12; }
.hero-copy h1,
.page-hero h1,
.source-hero h1 {
  margin: 0;
  font-size: clamp(3rem, 6.7vw, 6.7rem);
  line-height: .98;
  letter-spacing: -.065em;
}

.hero-copy h1 {
  max-width: 980px;
}

.hero-text,
.page-hero p,
.source-hero p {
  max-width: 760px;
  font-size: clamp(1.08rem, 2vw, 1.42rem);
  color: #33413b;
}

.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 28px;
}

.button {
  min-height: 46px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 999px;
  padding: 12px 17px;
  text-decoration: none;
  border: 1px solid var(--line);
  font-weight: 900;
}
.button.primary { background: var(--ink); color: var(--paper); border-color: var(--ink); }
.button.secondary { background: var(--paper); color: var(--ink); }
.button.ghost { background: transparent; color: var(--green-dark); }

.truth-orbit {
  position: relative;
  min-height: 520px;
  border-radius: var(--radius-xl);
  background:
    linear-gradient(135deg, rgba(13, 112, 105, .12), rgba(197, 130, 40, .12)),
    rgba(255, 250, 240, .7);
  border: 1px solid var(--line);
  box-shadow: var(--shadow);
  overflow: hidden;
}

.truth-orbit::before {
  content: "";
  position: absolute;
  inset: 70px;
  border: 1px dashed rgba(23, 33, 29, .22);
  border-radius: 50%;
}

.orbit-card {
  position: absolute;
  padding: 20px;
  border-radius: 24px;
  background: var(--paper);
  border: 1px solid var(--line);
  box-shadow: 0 18px 45px rgba(49, 38, 22, .12);
}

.orbit-card span {
  display: block;
  color: var(--green-dark);
  font-weight: 950;
}
.orbit-card p { margin: 6px 0 0; color: var(--muted); }
.orbit-card.core { left: 50%; top: 50%; transform: translate(-50%, -50%); text-align: center; }
.orbit-card.core strong { display: block; margin-top: 8px; max-width: 170px; }
.orbit-card.truth { left: 28px; top: 64px; max-width: 230px; }
.orbit-card.agent { right: 28px; bottom: 74px; max-width: 250px; }

.section-heading {
  display: grid;
  gap: 8px;
  margin-bottom: 22px;
}
.section-heading h2,
.mode-copy h2,
.story-panel h2,
.proof-panel h2,
.reading-lane h2,
.boundary-table h2,
.warning-panel h2 {
  margin: 0;
  font-size: clamp(2rem, 4vw, 4rem);
  letter-spacing: -.06em;
}
.section-heading p:last-child { margin: 0; color: var(--muted); max-width: 760px; }

.reader-paths,
.story-panel,
.mode-panel,
.proof-panel,
.library-preview,
.page-hero,
.choice-panel,
.reading-lane,
.boundary-table,
.warning-panel,
.source-drawer,
.example-panel {
  margin: 28px 0;
}

.path-grid {
  display: grid;
  grid-template-columns: 1.15fr .85fr;
  gap: 16px;
}
.path-card {
  min-height: 230px;
  padding: 24px;
  border-radius: var(--radius-lg);
  text-decoration: none;
  color: var(--ink);
  background: rgba(255, 250, 240, .76);
  border: 1px solid var(--line);
  box-shadow: var(--shadow);
  transition: transform .18s ease, box-shadow .18s ease;
}
.path-card:hover { transform: translateY(-4px); box-shadow: 0 30px 80px rgba(49, 38, 22, .18); }
.path-card.large { grid-row: span 2; }
.path-card span,
.card-number {
  display: inline-flex;
  width: 46px;
  height: 46px;
  align-items: center;
  justify-content: center;
  border-radius: 15px;
  background: var(--green-soft);
  color: var(--green-dark);
  font-weight: 950;
}
.path-card h3 { margin: 22px 0 10px; font-size: 1.7rem; letter-spacing: -.035em; }
.path-card p { margin: 0; color: var(--muted); }

.story-panel,
.mode-panel,
.proof-panel,
.library-preview,
.reading-lane,
.choice-panel,
.warning-panel,
.example-panel {
  padding: 30px;
  border-radius: var(--radius-xl);
  background: rgba(255, 250, 240, .72);
  border: 1px solid var(--line);
  box-shadow: var(--shadow);
}

.flow-line {
  display: grid;
  grid-template-columns: repeat(4, minmax(0, 1fr));
  gap: 12px;
}
.flow-line article,
.mode-grid article,
.briefing-card,
.run-cards article,
.decision-grid article {
  padding: 22px;
  border-radius: var(--radius-lg);
  background: var(--paper);
  border: 1px solid var(--line);
}
.flow-line span,
.timeline span,
.source-type {
  color: var(--clay);
  font-size: .76rem;
  font-weight: 950;
  text-transform: uppercase;
  letter-spacing: .12em;
}
.flow-line h3,
.mode-grid h3,
.briefing-card h2,
.run-cards h2,
.decision-grid h2 {
  margin: 12px 0 8px;
}
.flow-line p,
.mode-grid p,
.briefing-card p,
.run-cards p,
.decision-grid p {
  color: var(--muted);
}

.mode-panel {
  display: grid;
  grid-template-columns: .8fr 1.2fr;
  gap: 22px;
  align-items: stretch;
}
.mode-copy p { color: var(--muted); }
.mode-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 14px;
}
.tag-list {
  list-style: none;
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  padding: 0;
}
.tag-list li {
  padding: 7px 10px;
  border-radius: 999px;
  background: var(--green-soft);
  color: var(--green-dark);
  font-size: .86rem;
  font-weight: 850;
}

.proof-panel {
  display: grid;
  grid-template-columns: 1fr 1.1fr;
  gap: 22px;
}
.proof-panel p { color: var(--muted); }
.source-picks,
.source-strip {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  align-items: center;
}
.source-picks a,
.source-strip a,
.related-card a {
  padding: 10px 12px;
  border-radius: 999px;
  background: var(--paper);
  border: 1px solid var(--line);
  text-decoration: none;
  font-weight: 850;
}

.docs-toolbar {
  display: grid;
  grid-template-columns: 1fr minmax(260px, 420px);
  gap: 20px;
  align-items: end;
}
.search-box {
  display: grid;
  gap: 6px;
  color: var(--muted);
  font-size: .86rem;
  font-weight: 850;
}
input[type="search"], select {
  min-height: 46px;
  border: 1px solid var(--line);
  border-radius: 15px;
  background: var(--paper);
  padding: 10px 12px;
  font: inherit;
  color: var(--ink);
}

.doc-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
  margin: 22px 0;
}
.source-card a {
  min-height: 230px;
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 18px;
  border-radius: var(--radius-lg);
  background: var(--paper);
  color: var(--ink);
  text-decoration: none;
  border: 1px solid var(--line);
}
.source-card h3 { margin: 0; font-size: 1.14rem; }
.source-card p { margin: 0; color: var(--muted); font-size: .93rem; }
.source-card code { margin-top: auto; color: var(--muted); font-size: .76rem; word-break: break-all; }

.page-hero,
.source-hero {
  padding: 56px 0 34px;
}
.briefing-grid,
.run-cards,
.decision-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
  margin: 24px 0;
}
.briefing-card.highlight {
  grid-column: span 1;
  background: var(--ink);
  color: var(--paper);
}
.briefing-card.highlight p,
.briefing-card.highlight .card-number { color: var(--paper); }

.big-list {
  margin: 0;
  padding-left: 28px;
  font-size: 1.08rem;
}
.big-list li { margin: 12px 0; color: #303d37; }
.big-list.compact li { font-size: 1rem; }

.tab-buttons {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 12px;
}
.tab-button {
  border: 1px solid var(--line);
  border-radius: 999px;
  padding: 10px 13px;
  background: var(--paper);
  cursor: pointer;
  font-weight: 900;
}
.tab-button.active {
  background: var(--ink);
  color: var(--paper);
  border-color: var(--ink);
}
.tab-panel {
  display: none;
  padding: 22px;
  border-radius: var(--radius-lg);
  background: var(--paper);
  border: 1px solid var(--line);
}
.tab-panel.active { display: block; }
.tab-panel h3 { margin-top: 0; }

.architecture-map,
.timeline {
  display: grid;
  gap: 12px;
  margin: 24px 0;
}
.layer,
.timeline article {
  display: grid;
  grid-template-columns: 66px .55fr 1fr;
  gap: 18px;
  align-items: center;
  padding: 18px;
  border-radius: var(--radius-lg);
  background: rgba(255, 250, 240, .76);
  border: 1px solid var(--line);
}
.layer span {
  width: 54px;
  height: 54px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border-radius: 18px;
  background: var(--green-soft);
  color: var(--green-dark);
  font-weight: 950;
}
.layer h2,
.timeline h2 { margin: 0; }
.layer p,
.timeline p { margin: 0; color: var(--muted); }

.split-explain,
.boundary-table {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 18px;
  margin: 28px 0;
}
.split-explain article,
.table-card {
  padding: 26px;
  border-radius: var(--radius-xl);
  background: rgba(255, 250, 240, .76);
  border: 1px solid var(--line);
  box-shadow: var(--shadow);
}
table {
  width: 100%;
  border-collapse: collapse;
}
th, td {
  padding: 12px;
  border-bottom: 1px solid var(--line);
  text-align: left;
  vertical-align: top;
}
th { color: var(--clay); }

pre {
  position: relative;
  overflow: auto;
  padding: 18px;
  border-radius: 18px;
  background: #16201c;
  color: #f4fbf5;
}
.copy-code {
  position: absolute;
  top: 10px;
  right: 10px;
  border: 0;
  border-radius: 999px;
  padding: 6px 10px;
  background: var(--green);
  color: white;
  cursor: pointer;
  font-weight: 850;
}
.copy-example {
  justify-self: start;
  border: 0;
  border-radius: 999px;
  padding: 10px 14px;
  background: var(--green-dark);
  color: white;
  cursor: pointer;
  font-weight: 900;
}
.example-panel.refined {
  display: grid;
  grid-template-columns: .8fr 1.2fr;
  gap: 24px;
}
.example-builder {
  display: grid;
  gap: 12px;
}
.example-builder label {
  display: grid;
  gap: 6px;
  color: var(--muted);
  font-weight: 850;
}
.example-output { min-height: 250px; margin: 0; }

.source-page {
  width: var(--content);
}
.source-hero {
  min-height: 420px;
}
.readable-layout {
  display: grid;
  grid-template-columns: 310px minmax(0, 1fr);
  gap: 20px;
  align-items: start;
}
.readable-aside {
  position: sticky;
  top: 92px;
  display: grid;
  gap: 12px;
}
.aside-card,
.insight-card,
.chapter-card {
  padding: 18px;
  border-radius: var(--radius-lg);
  background: rgba(255, 250, 240, .8);
  border: 1px solid var(--line);
}
.aside-card h2,
.insight-card h2 { margin-top: 0; }
.aside-card ul { padding-left: 18px; }
.aside-card li,
.aside-card p,
.insight-card p,
.chapter-card p { color: var(--muted); }
.insight-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}
.chapter-section {
  margin-top: 22px;
  padding: 26px;
  border-radius: var(--radius-xl);
  background: rgba(255, 250, 240, .62);
  border: 1px solid var(--line);
  box-shadow: var(--shadow);
}
.chapter-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 12px;
}
.chapter-card h3 { margin-top: 0; }
.related-card {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.related-card .kicker { margin-bottom: 0; }

.source-drawer {
  margin: 34px 0 60px;
  border-radius: var(--radius-xl);
  background: rgba(255, 250, 240, .78);
  border: 1px solid var(--line);
  box-shadow: var(--shadow);
  overflow: hidden;
}
.source-drawer summary {
  cursor: pointer;
  list-style: none;
  padding: 24px 30px;
  display: flex;
  justify-content: space-between;
  gap: 18px;
  align-items: center;
}
.source-drawer summary span {
  font-size: 1.35rem;
  font-weight: 950;
}
.source-drawer summary strong {
  color: var(--muted);
  font-size: .94rem;
}
.markdown-body {
  padding: 10px 34px 42px;
  max-width: 920px;
}
.markdown-body h1 { display: none; }
.markdown-body h2 {
  margin-top: 42px;
  padding-top: 12px;
  border-top: 1px solid var(--line);
  font-size: 1.8rem;
}
.markdown-body h3 { margin-top: 28px; }
.markdown-body p,
.markdown-body li { color: #303d37; }
.markdown-body blockquote {
  margin: 18px 0;
  padding: 14px 16px;
  border-left: 5px solid var(--green);
  background: var(--green-soft);
  border-radius: 0 16px 16px 0;
}
.markdown-body table {
  display: block;
  width: 100%;
  overflow-x: auto;
}
.markdown-body :not(pre) > code,
.site-footer code {
  padding: .12em .34em;
  border-radius: 7px;
  background: var(--green-soft);
  color: var(--green-dark);
}
.missing-link {
  padding: .1em .34em;
  border-radius: 7px;
  background: #f8e8d6;
  color: #8f3f1d;
  cursor: help;
}
.empty-state { color: var(--muted); }
.site-footer {
  padding: 26px 0 46px;
  color: var(--muted);
}

@media (max-width: 980px) {
  :root { --content: min(100vw - 24px, 760px); }
  .site-header,
  .hero-stage,
  .mode-panel,
  .proof-panel,
  .docs-toolbar,
  .example-panel.refined,
  .readable-layout,
  .split-explain,
  .boundary-table {
    grid-template-columns: 1fr;
  }
  .truth-orbit { min-height: 420px; }
  .path-grid,
  .flow-line,
  .mode-grid,
  .doc-grid,
  .briefing-grid,
  .run-cards,
  .decision-grid,
  .insight-grid,
  .chapter-grid {
    grid-template-columns: 1fr;
  }
  .path-card.large { grid-row: auto; }
  .layer,
  .timeline article {
    grid-template-columns: 1fr;
  }
  .readable-aside { position: static; }
  .hero-copy h1,
  .page-hero h1,
  .source-hero h1 {
    font-size: clamp(2.6rem, 14vw, 4.4rem);
  }
}
"""


EXPERIENCE_JS = r"""
(function () {
  const searchInput = document.querySelector("[data-doc-search]");
  const cards = Array.from(document.querySelectorAll("[data-search]"));
  const emptyState = document.querySelector("[data-empty-state]");

  function filterCards() {
    if (!cards.length) return;
    const query = (searchInput && searchInput.value ? searchInput.value : "").trim().toLowerCase();
    let visible = 0;
    cards.forEach((card) => {
      const haystack = card.dataset.search || "";
      const show = !query || haystack.includes(query);
      card.hidden = !show;
      if (show) visible += 1;
    });
    if (emptyState) emptyState.hidden = visible !== 0;
  }
  if (searchInput) searchInput.addEventListener("input", filterCards);

  document.querySelectorAll("[data-tabs]").forEach((root) => {
    const buttons = Array.from(root.querySelectorAll("[data-tab]"));
    const panels = Array.from(root.querySelectorAll("[data-tab-panel]"));
    buttons.forEach((button) => {
      button.addEventListener("click", () => {
        const key = button.dataset.tab;
        buttons.forEach((item) => item.classList.toggle("active", item === button));
        panels.forEach((panel) => panel.classList.toggle("active", panel.dataset.tabPanel === key));
      });
    });
  });

  document.querySelectorAll("pre").forEach((pre) => {
    if (pre.querySelector(".copy-code")) return;
    const button = document.createElement("button");
    button.className = "copy-code";
    button.type = "button";
    button.textContent = "复制";
    button.addEventListener("click", async () => {
      const text = pre.innerText.replace(/^复制\s*/, "");
      try {
        await navigator.clipboard.writeText(text);
        button.textContent = "已复制";
        setTimeout(() => (button.textContent = "复制"), 1200);
      } catch (error) {
        button.textContent = "复制失败";
        setTimeout(() => (button.textContent = "复制"), 1200);
      }
    });
    pre.appendChild(button);
  });

  const endpoint = document.getElementById("example-endpoint");
  const scope = document.getElementById("example-scope");
  const output = document.getElementById("example-output");
  const copyExample = document.querySelector("[data-copy-example]");

  const scopes = {
    photo: {
      query: "fixing time 怎么生成？",
      input: "Failed message mentions fixing time cutoff and NDF settlement.",
      channel: "tradition",
      product: "stella",
      pack: "fxd-ndf-cutoff-fixing",
      domain: "cutoff-fixing"
    },
    payments: {
      query: "payment amount 怎么生成？",
      input: "src.amount=123.45\nsrc.currency=USD",
      channel: "tradition",
      product: "stella",
      pack: "payments",
      domain: "core"
    }
  };

  function scopeJson(selected) {
    return `{
      "channel": "${selected.channel}",
      "product": "${selected.product}",
      "pack": "${selected.pack}",
      "domain": "${selected.domain}"
    }`;
  }

  function buildExample() {
    if (!endpoint || !scope || !output) return;
    const selectedScope = scopes[scope.value] || scopes.photo;
    const endpointValue = endpoint.value;

    if (endpointValue === "mcp") {
      output.textContent = "curl -s http://localhost:8080/mcp/tools | jq";
      return;
    }

    if (endpointValue === "scenario") {
      output.textContent = `curl -sS -X POST http://localhost:8080/api/v1/scenario/analyze-failed-message \\
  -H 'Content-Type: application/json' \\
  -H 'X-RTS-API-Key: tester-key' \\
  -d '{
    "input": "${selectedScope.input.replace(/\n/g, "\\n")}",
    "caller_id": "tester",
    "scope": ${scopeJson(selectedScope)},
    "output_mode": "default",
    "max_objects": 5
  }' | jq`;
      return;
    }

    const path = endpointValue === "ask" ? "/api/v1/ask" : "/api/v1/query";
    const llmFlag = endpointValue === "ask" ? "true" : "false";
    output.textContent = `curl -sS -X POST http://localhost:8080${path} \\
  -H 'Content-Type: application/json' \\
  -H 'X-RTS-API-Key: tester-key' \\
  -d '{
    "query": "${selectedScope.query}",
    "caller_id": "tester",
    "scope_hint": ${scopeJson(selectedScope)},
    "output_mode": "default",
    "use_llm": ${llmFlag}
  }' | jq`;
  }

  if (endpoint && scope && output) {
    endpoint.addEventListener("change", buildExample);
    scope.addEventListener("change", buildExample);
    buildExample();
  }
  if (copyExample && output) {
    copyExample.addEventListener("click", async () => {
      try {
        await navigator.clipboard.writeText(output.textContent || "");
        copyExample.textContent = "已复制";
        setTimeout(() => (copyExample.textContent = "复制示例"), 1200);
      } catch (error) {
        copyExample.textContent = "复制失败";
        setTimeout(() => (copyExample.textContent = "复制示例"), 1200);
      }
    });
  }
})();
"""


if __name__ == "__main__":
    build_experience_site()
